networks:
  event-driven-net:
    external: true
    name: event-driven-net

services:
  payments-service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8082
    volumes:
      - .:/app
    networks:
      - event-driven-net
    restart: always
